"""empty message

Revision ID: 14e6b045e309
Revises: a241bfa801ea
Create Date: 2021-05-24 20:35:14.684798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e6b045e309'
down_revision = 'a241bfa801ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivation_word_section',
    sa.Column('m_w_id', sa.Integer(), nullable=False),
    sa.Column('m_w_description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('m_w_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motivation_word_section')
    # ### end Alembic commands ###
