"""empty message

Revision ID: 2e756a7c2a4c
Revises: 7ab5b93b774d
Create Date: 2021-05-29 12:42:10.746738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e756a7c2a4c'
down_revision = '7ab5b93b774d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('p_r_price', sa.String(length=250), nullable=False))
    op.drop_column('products', 'p_r_tags')
    op.drop_column('products', 'p_r_link')
    op.drop_column('products', 'p_r_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('p_r_data', sa.DATETIME(), nullable=True))
    op.add_column('products', sa.Column('p_r_link', sa.VARCHAR(length=250), nullable=False))
    op.add_column('products', sa.Column('p_r_tags', sa.VARCHAR(length=250), nullable=False))
    op.drop_column('products', 'p_r_price')
    # ### end Alembic commands ###
