"""empty message

Revision ID: 6c1dccb9879b
Revises: 
Create Date: 2021-05-28 07:12:57.932084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1dccb9879b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_c_title', sa.String(length=50), nullable=False),
    sa.Column('p_c_description', sa.String(length=250), nullable=False),
    sa.Column('p_c_link', sa.String(length=250), nullable=False),
    sa.Column('p_c_link_title', sa.String(length=250), nullable=False),
    sa.Column('p_c_image', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('own_title', sa.String(length=50), nullable=False),
    sa.Column('own_description', sa.String(length=250), nullable=False),
    sa.Column('own_image', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_title', sa.String(length=50), nullable=False),
    sa.Column('p_description', sa.Text(), nullable=False),
    sa.Column('p_data', sa.DateTime(), nullable=True),
    sa.Column('p_tags', sa.String(length=250), nullable=False),
    sa.Column('p_link', sa.String(length=250), nullable=False),
    sa.Column('p_image', sa.String(length=250), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('owner')
    op.drop_table('category')
    # ### end Alembic commands ###
