"""empty message

Revision ID: 7ab5b93b774d
Revises: 6c1dccb9879b
Create Date: 2021-05-29 12:35:36.987764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab5b93b774d'
down_revision = '6c1dccb9879b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_r_c_title', sa.String(length=50), nullable=False),
    sa.Column('p_r_c_description', sa.String(length=250), nullable=False),
    sa.Column('p_r_c_link', sa.String(length=250), nullable=False),
    sa.Column('p_r_c_link_title', sa.String(length=250), nullable=False),
    sa.Column('p_r_c_image', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_r_title', sa.String(length=50), nullable=False),
    sa.Column('p_r_description', sa.Text(), nullable=False),
    sa.Column('p_r_data', sa.DateTime(), nullable=True),
    sa.Column('p_r_tags', sa.String(length=250), nullable=False),
    sa.Column('p_r_link', sa.String(length=250), nullable=False),
    sa.Column('p_r_image', sa.String(length=250), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('pr_category')
    # ### end Alembic commands ###
