"""empty message

Revision ID: a241bfa801ea
Revises: 
Create Date: 2021-05-24 20:33:41.285366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a241bfa801ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_section',
    sa.Column('a_s_id', sa.Integer(), nullable=False),
    sa.Column('a_s_title', sa.String(length=50), nullable=False),
    sa.Column('a_s_description', sa.Text(), nullable=False),
    sa.Column('a_s_link', sa.String(length=250), nullable=False),
    sa.Column('a_s_link_title', sa.String(length=250), nullable=False),
    sa.Column('a_s_image', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('a_s_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_section')
    # ### end Alembic commands ###
